[build]
  command = "yarn build && yarn export"
  functions = "functions"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "yarn dev"
  port = 8888
  targetPort = 7777

[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set,
  # or the root directory if a base hasn’t been set.
  directory = "functions/"
  included_files = ["functions/contact-template.html"]

[[redirects]]
  from = "/api/contact-us"
  to = "/.netlify/functions/contact-us"
  status = 200
